
services:
  - type: web
    name: crep-online
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
