services:
  - type: web
    name: crep-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    rootDir: Serveur
    envVars:
      - key: PORT
        value: 10000