services:
  - type: web
    name: simulation-crep
    env: python
    plan: free
    region: par
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
